# Usa una imagen base de Python en Debian Buster
FROM python:3.9-buster

# Establece la variable de entorno DEBIAN_FRONTEND a noninteractive para evitar las preguntas durante la instalación
ENV DEBIAN_FRONTEND=noninteractive

# Instala dependencias necesarias
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    apache2 \
    apache2-dev \
    gcc \
    libpq-dev \
    libapache2-mod-wsgi-py3 \
    curl \
    gnupg \
    lsb-release \
    apt-transport-https \
    make \
    nano \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo
WORKDIR /var/www/html/app

# Copia los archivos de la aplicación al contenedor
COPY API.py /var/www/html/app/
COPY wsgi.py /var/www/html/app/
COPY requirements.txt /var/www/html/app/
COPY templates /var/www/html/app/templates/
COPY apache-config/000-default.conf /etc/apache2/sites-available/000-default.conf

# Habilita el sitio y el módulo WSGI
RUN a2ensite 000-default && a2enmod wsgi

# Instala las dependencias de la aplicación
RUN pip install --no-cache-dir -r /var/www/html/app/requirements.txt

# Expone el puerto 8888
EXPOSE 8888

# Comando para ejecutar Apache en el primer plano
CMD ["apache2ctl", "-D", "FOREGROUND"]

